In [1]:
import numpy as np

In [17]:
#N1
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
#N2
mean_a = a.mean(axis = 0)

In [5]:
mean_a

array([2. , 8.4])

In [8]:
#N3
a_centered = np.subtract(a, mean_a)

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [9]:
a1 = a_centered[:,0]
a2 = a_centered[:,1]
a_centered_sp = np.dot(a1,a2)

In [10]:
a_centered_sp

8.0

In [12]:
N = a.shape[0]

In [13]:
N

5

In [14]:
my_cov = a_centered_sp/(N-1)

In [15]:
my_cov

2.0

In [16]:
#N4
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])